version: "3.8"
services:
  client:
    image: node:lts-alpine
    container_name: face3d-client
    working_dir: /work
    ports:
      - 3000:8080
    volumes:
      - ./client:/work
    command: /bin/sh -c "yarn install && yarn serve"
