version: "3.8"
services:
  client:
    image: node:lts-alpine
    container_name: face3d-client
    working_dir: /work
    ports:
      - 3000:8080
    volumes:
      - ./client:/work
    command: /bin/sh -c "yarn install && yarn serve"
  server:
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    container_name: face3d-server
    working_dir: /work
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - ./server:/work
    command: denon run --allow-net --allow-write --allow-read --allow-env main.ts
